# Generated by Django 4.2.5 on 2023-09-10 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectDescription', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityDescription', models.CharField(max_length=2000)),
                ('Task', models.CharField(max_length=200)),
                ('Duration', models.IntegerField()),
                ('ActualCost', models.IntegerField()),
                ('Actual_Complete', models.FloatField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDepedency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromActivity', models.IntegerField()),
                ('ToActivity', models.IntegerField()),
                ('DepedencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectactivity')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdata'),
        ),
    ]
