# Generated by Django 4.1.1 on 2023-09-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_projectactivity_projectdepedency_userdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='PlannedCost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
