# Generated by Django 4.2.5 on 2023-09-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectactivity_plannedcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdepedency',
            name='DepedencyID',
        ),
        migrations.AlterField(
            model_name='projectdepedency',
            name='FromActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectactivity'),
        ),
        migrations.AlterField(
            model_name='projectdepedency',
            name='ToActivity',
            field=models.IntegerField(verbose_name=False),
        ),
    ]
