# Generated by Django 4.2.5 on 2023-09-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
    ]
