# Generated by Django 4.1.1 on 2023-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectName',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
