# Generated by Django 4.1.1 on 2023-09-13 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project_projectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivity',
            name='ActivityDescription',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='Task',
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='depedency',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='endDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
